version: "3.8"

services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    networks:
      - smartlib-net

  book-service:
    build: ./book-service
    ports:
      - "8082:8082"
    networks:
      - smartlib-net

  loan-service:
    build: ./loan_service
    ports:
      - "8083:8083"
    networks:
      - smartlib-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - user-service
      - book-service
      - loan-service
    networks:
      - smartlib-net

networks:
  smartlib-net:
