version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    env_file:
      - ./user-service/.env
    restart: always

  book-service:
    build: ./book-service
    ports:
      - "8082:8082"
    env_file:
      - ./book-service/.env
    restart: always

  loan-service:
    build: ./loan_service
    ports:
      - "8083:8083"
    env_file:
      - ./loan_service/.env
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8000:80" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - user-service
      - book-service
      - loan-service
