version: "3.8"

services:
  user-service:
    image: tashrif2001/smartlibrary:user-service
    ports:
      - "8081:8081"
    networks:
      - smartlib-overlay
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  book-service:
    image: tashrif2001/smartlibrary:book-service
    ports:
      - "8082:8082"
    networks:
      - smartlib-overlay
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  loan-service:
    image: tashrif2001/smartlibrary:loan-service
    ports:
      - "8083:8083"
    networks:
      - smartlib-overlay
    environment:
      USER_SERVICE_URL: http://user-service:8081
      BOOK_SERVICE_URL: http://book-service:8082
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "/home/tashrif/Desktop/SEM-6/Distributed Systems-601/smartlibrary/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    networks:
      - smartlib-overlay
    depends_on:
      - user-service
      - book-service
      - loan-service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  smartlib-overlay:
    driver: overlay
    attachable: true
